aliases:
  - &project_path /go/src/github.com/aeternas/SwadeshNess-packages
  - &get_deps go get -v -t -d ./...
  - &docker_worker
    - image: circleci/golang:$GOLANG_VERSION
  - &git_checkout
    name: Checkout
    command: |
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config && \
      git clone --depth 1 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git reset --hard $CIRCLE_SHA1
  - &lint
    name: Install & Execute linter
    command: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest && \
        golangci-lint run
  - &test
    name: tests
    command: go test -v ./...
  - &attach_workspace
    at: *project_path
  - &persist_to_workspace
    root: .
    paths:
      - .

version: 2.1
jobs:
  checkout:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - run: *git_checkout
      - run: *get_deps
      - persist_to_workspace: *persist_to_workspace
  lint:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - attach_workspace: *attach_workspace
      - run: *lint
  unit_tests:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - attach_workspace: *attach_workspace
      - run: *test
workflows:
  version: 2.1
  lint-tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - unit_tests:
          requires:
            - checkout
