aliases:
  - &project_path /go/src/github.com/aeternas/SwadeshNess-packages
  - &get_deps go get -v -t -d ./...
  - &docker_worker
    - image: circleci/golang:1.11
  - &git_checkout
    name: Checkout
    command: |
      mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      git clone --depth=50 -b $CIRCLE_BRANCH $CIRCLE_REPOSITORY_URL ./ && \
      git checkout $CIRCLE_SHA1
  - &lint
    name: linting
    command: go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run
  - &test
    name: tests
    command: go test -v ./...
  - &attach_workspace
    at: *project_path
  - &persist_to_workspace
    root: .
    paths:
      - .

version: 2
jobs:
  checkout:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - run: *git_checkout
      - run: *get_deps
      - persist_to_workspace: *persist_to_workspace
  lint:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - attach_workspace: *attach_workspace
      - run: *lint
  unit_tests:
    docker: *docker_worker
    working_directory: *project_path
    steps:
      - attach_workspace: *attach_workspace
      - run: *test
workflows:
  version: 2
  lint-tests:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - unit_tests:
          requires:
            - checkout
